version: "3"

services:
  backend:
    container_name: tem-dev-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/data/backend
    command: gunicorn --bind :8000 backend.wsgi:application --reload

  web:
    container_name: tem-dev-web
    tty: true
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./clients/web:/data/web
      - ./clients/.env:/data/web/.env

  database:
    container_name: tem-dev-database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - "MYSQL_DATABASE=travel_expense_manager"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

  adminer:
    container_name: tem-dev-adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  dbdata:
