version: "3"

services:
  backend:
    container_name: tem-testing-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/data/backend
    command: gunicorn --bind :8000 backend.wsgi:application

  web:
    container_name: tem-testing-web
    tty: true
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./clients/web:/data/web
      - ./clients/.env:/data/web/.env
    command: sh -c "npm install && npm run build && npm run prod"

  database:
    container_name: tem-testing-database
    image: mysql:5.7
    volumes:
      - dbtestingdata:/var/lib/mysql
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - "MYSQL_DATABASE=travel_expense_manager"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  adminer:
    container_name: tem-testing-adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  dbtestingdata:
